name: Deploy Application

on:
  push:
    branches:
      - main
      - feat/AWS_workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Upload application to S3 (Optional)
        run: |
          aws s3 cp ./ s3://your-bucket-name/ --recursive

      - name: Copy code to EC2 instance via SCP
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Execute SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y python3-pip  # Example of installing dependencies
            cd /home/ec2-user/app
            nohup python3 app.py &  # Replace with your command to run the app