name: Deploy Dockerized Python Web App to EC2

on:
  push:
    branches:
      - main
      - feat/AWS_workflow

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: SSH into EC2 and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance public IP
          username: ${{ secrets.EC2_USER }}  # Replace with your EC2 username (e.g., ec2-user or ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}  # Replace with your EC2 private SSH key
          script: |
            # Update the EC2 instance
            sudo apt-get update -y

            # Install Docker if not installed
            if ! [ -x "$(command -v docker)" ]; then
              sudo apt-get install -y docker.io
            fi

            # Create a directory for the app, sync code from GitHub
            mkdir -p ~/app
            cd ~/app

            # Remove old code and copy the new code
            rm -rf *
            scp -r ${{ github.workspace }}/* ~/app

            # Stop any running containers
            docker stop python-web-app || true
            docker rm python-web-app || true

            # Build Docker image from the new code
            docker build -t python-web-app .

            # Run the Docker container
            docker run -d --name python-web-app -p 80:80 python-web-app

            # Verify the container is running
            docker ps