name: Run test workflow

on:
  pull_request:
    branches:
      - main
      - feat/**

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt
        pip install pytest
        pip install python-multipart
        pip install flake8

    - name: Run tests
      run: |
        pytest test/

    - name: Run flake8
      run: flake8 .

